- title: "TaniaJekyll"
  url: "https://github.com/dinhanhthi/TaniaJekyll"
  description: "Một theme Jekyll đẹp dành cho trang web cá nhân dựa trên Bootstrap 4.1"
  img: "tania-jekyll.svg"
- title: "NoteTheme"
  url: "https://github.com/dinhanhthi/NoteTheme"
  description: "Một theme Jekyll dành riêng cho việc ghi chú dựa trên Matjek."
  img: "notetheme.svg"
- title: "NXFEM"
  url: "https://github.com/dinhanhthi/nxfem"
  description: "Matlab toolbox dành cho phương pháp Nistche-Extended Finite Element Method."
  img: "nxfem.png"
- title: "Tôi Tự Học"
  url: "https://toituhoc.xyz/about"
  description: "Trang web tiếng Việt chia sẻ về Toán và Tin học dưới phong cách \"tự học từ lúc chưa biết gì\"."
  img: "toituhoc.png"
- title: "Math2IT"
  url: "http://math2it.com/gioi-thieu"
  description: "Trang web Toán học, Công nghệ và Giáo dục dưới dạng trực quan, dễ hiểu."
  img: "math2it.png"

