- title: "TaniaJekyll"
  url: "https://github.com/dinhanhthi/TaniaJekyll"
  description: "A beautiful personal jekyll theme based on Bootstrap 4.1."
  img: "tania-jekyll.svg"
- title: "NoteTheme"
  url: "https://github.com/dinhanhthi/NoteTheme"
  description: "A Jekyll theme designed only for taking note."
  img: "notetheme.svg"
- title: "NXFEM"
  url: "https://github.com/dinhanhthi/nxfem"
  description: "A Matlab library for Nitsche - Extended Finite Element Method."
  img: "nxfem.png"
- title: "Math2IT"
  url: "http://math2it.com/gioi-thieu"
  description: "A Vietnamese site for intuitive knowledge (Maths, LaTeX, Education and Technology)."
  img: "math2it.gif"

