- title: "TaniaJekyll"
  url: "https://github.com/dinhanhthi/TaniaJekyll"
  description: "A beautiful personal jekyll theme based on Bootstrap 4.1"
  img: "tania-jekyll.svg"
- title: "NoteTheme"
  url: "https://github.com/dinhanhthi/NoteTheme"
  description: "An useful jekyll theme for note-taking."
  img: "notetheme.svg"
- title: "Tôi Tự Học"
  url: "https://toituhoc.xyz/about"
  description: "A Vietnamese site where I write all about Maths and Information Technology for the beginners in an intuitive style."
  img: "toituhoc.png"
- title: "Math2IT"
  url: "http://math2it.com/gioi-thieu"
  description: "A Vietnamese site for intuitive knowledge (Maths, LaTeX, Education and Technology)."
  img: "math2it.gif"

